name: Android

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: pnpm
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build glslang-tools
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          link-to-sdk: false
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: CI
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: pnpm exec nx build-android hello
