name: ci

on:
  push:
  pull_request:

jobs:
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: pnpm
      - name: Install Ninja
        run: brew install ninja
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm exec nx run-many -t test --output-style=stream
      - name: Build hello
        run: pnpm exec nx build hello
      - name: Build hello software
        run: pnpm exec nx build-software hello
